apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: database
  namespace: default
  labels:
    app: database
    version: 12.1.0.2
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: database
      version: 12.1.0.2
  template:
    metadata:
      name: database
      labels: 
        app: database
        version: 12.1.0.2
    spec:
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      containers: 
      - name: database
        command: 
        - /home/oracle/setup/dockerInit.sh
        image: quay.io/ravi_r_singhal/database:12.1.0.2
        resources:
          requests:
            memory: 10Gi
        ports:
        - containerPort: 1521
          hostPort: 1521
        volumeMounts:
          - mountPath: /dev/shm
            name: dshm
        env:
          - name: DB_SID 
            value: OraDoc
          - name: DB_PDB
            value: OraPdb 
          - name: DB_PASSWD
            value: Welcome1 
          - name: DB_DOMAIN
            value: my.domain.com
          - name: DB_BUNDLE
            value: basic
          - name: DB_MEMORY
            value: 8g
      imagePullSecrets: 
      - name: regsecret
